eureka:
  host: localhost
  port: 8762
  client:
    healthcheck:
             enable: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
spring:
  cloud:
    stream:
      kafka:
        binder:
           broker: localhost:9093
           zkNodes: localhost:2182
management:
  security:
    enabled: true